### ISSUE TITLE
merge request plan

### ISSUE THREAD

**Issue by shincurry** [ccloli/animeloop-cli-msvc#1]
Do you have plans to merge this commit about Windows build support into the main repo of animeloop-cli?

We could use preprocessor directives to achieve this.

**Comment by ccloli** [comment]
Hi, at first, thanks for creating animeloop-cli, which is a nice tool :-)

However I'm not familiar with C++, and the code is just copied from StackOverflow and Microsoft Docs. So the modification is just to make it works on Windows, and only fits for my case without any other testing. As I'm posting my code here is just for fun, so the answer is it's up to you.

If you'd like to use the commit, it should be noted that:

1. The code is for MSVC (Microsoft Visual C++) compiler (or say Microsoft Visual Studio) only, so if a user wants to compile the project for Windows, he may only uses MSVC to compile instead of some other toolchains like MinGW. And as you can see, to configure the dependence for Visual Studio is a bit annoying. Maybe it's better to find a more general way to replace `fork()` and `CreateProcess()` (or as a fallback, like [animeloop-cli-mingw](https://github.com/ccloli/animeloop-cli-mingw) which uses `system()` directly), so that it can suit for more build environments?

2. One thing I didn't note on readme file is to make it compatible with `CreateProcess()`, I changed the arguments passed to `child_process()`. Instead of `function`, `child_process()` is now accepting a `string` as the CLI parameter for `CreateProcess()`. So if you want to keep the changes on `child_process()`, it's better to keep using a same way to pass the child process configuration to `child_process()` on different targets, and it should be worth to make the code tidy.

3. The way to detect FFmpeg is a bit different on Windows, as Windows has a CLI `where` to find the file, while on *nix we uses `which`. But that should be fine, as it can be adapted by using preprocessor simply.

If you've any question, feel free to ask :-)

**Comment by shincurry** [comment]
Thank you.

I am going to use [animeloop-cli-mingw](https://github.com/ccloli/animeloop-cli-mingw) this one as base code of branch `feature/windows-build` of main repo.

I have read README and still don't know how to install dependency and build in Windows. I am very unfamiliar with the Windows development environment.
i have no idea how to use pacman in Windows, is not pacman only available in Arch Linux?

Could you please tell me the right steps?

**Comment by ccloli** [comment]
If you'd like to cross compile on Linux (like this [FFmpeg prebuilt binaries for Windows](https://ffmpeg.zeranoe.com/)), you should use MinGW, and you can search some keywords like `linux cross compile mingw w64`. Most of Linux distributions have the cross compile toolchains, like on [this article](http://recursiveg.me/2014/02/how-to-cross-compile-libcurl-on-linux/) says on Arch Linux you can try `pacman -S mingw-w64` to get the MinGW-w64 environments. However to cross compile on Linux, you may need to build most of the dependencies by yourself.

If you'd like to build on Windows directly, it's recommended to use [MSYS2](https://www.msys2.org/) which comes with a package manager `pacman` which helps you to easily download and manage the packages inside MSYS2, so you can use the MSYS2 terminal just like using Arch Linux. MSYS2 also includes `MSYS`, `MINGW32` and `MINGW64` environments, so don't mess them up.

As I known, MSYS environment is modified from Cygwin, so it has most of the features in Cygwin, which means you can compile most of the Linux program on Cygwin/MSYS directly, as it simulates most of the Linux utilities (however I built `animeloop-cli` failed on it😂). MinGW doesn't come with MSYS, so it's not available to use Linux-only APIs, but should be fine to use Windows API. You can search `msys mingw difference` to get more details.

As MSYS2 has 3 environments, you should open `MSYS2 MinGW 64-bit` to use the `MINGW64` environment, and prefer to download the packages for MinGW-w64 only (their packages name will be prefixed with `mingw-w64-x86_64-`), or it'll be failed when linking to shared libraries. Packages for different environments will be saved to different directory (like the default MSYS packages will be saved to `/bin`, `/usr`, etc., and MinGW-w64 packages will be with a `/mingw64` prefix, e.g. `/mingw64/bin`), and when compiling they're not compatible with each other, so please make sure you've run MSYS2 on the wanted environment and install the fitted packages. You can checkout your current environment on terminal, and use `pacman -Ss [package-name]` before installing a package to check out what packages can be installed. 

![image](https://user-images.githubusercontent.com/8115912/56846921-9eb72100-6907-11e9-88bc-a9e02f4c7b0b.png)

![image](https://user-images.githubusercontent.com/8115912/56847184-7f6dc300-690a-11e9-9604-76f5d8cf5bf7.png)

`pacman` will install the latest packages by default, like when you're installing OpenCV with `pacman -S mingw-w64-x86_64-opencv`, you'll get OpenCV 4.0.1, so if you want to install a specific version package, you can refer to the source list (like the  USTC one: https://mirrors.ustc.edu.cn/msys2/mingw/x86_64/), copy the package link, and use `pacman -U [link]` to install the specific package.

Once you install MSYS2 (and run `pacman -Syu` and `pacman -Su` on MSYS2 terminal), you can follow [the steps](https://github.com/ccloli/animeloop-cli-mingw#windows-mingw) to download the dependencies, they're suit for MinGW-w64, so you'll need to launch `MSYS2 MinGW 64-bit`. 

By the way, if you want to use the MinGW version of animeloop-cli, the second note is still valid. I prefer to use the same way to define `child_process()` like using one of `child_process(std::string cli)` or `child_process(std::function<void()> functor)`, and use the same way to call `child_process()`. The code for different platform should only be defined inside `child_process()`.

**Comment by ccloli** [comment]
BTW, after Googling the details of MinGW, it seems that under MinGW you can use the Windows API. So I tried to build the MSVC one on MinGW, and it works. So animeloop-cli-msvc is not needed to use Visual Studio, you can compile it on MinGW. 😂

![image](https://user-images.githubusercontent.com/8115912/56847486-fa84a880-690d-11e9-883a-918e761a3cfb.png)

So maybe you can use the changes on [animeloop-cli-msvc](https://github.com/ccloli/animeloop-cli-msvc) for Windows, and use the changes on [animeloop-cli-mingw](https://github.com/ccloli/animeloop-cli-mingw) as fallback (like for Cygwin).

Maybe the repo should be renamed to `animeloop-cli-windows`, and `animeloop-cli-mingw` to `animeloop-cli-wtf-it-works`. 😂

**Comment by shincurry** [comment]
got your point, let me try.

love you. 😘

**Comment by shincurry** [comment]
🥳🥳🥳https://github.com/moeoverflow/animeloop-cli/pull/3

btw, are you interested in joining moeoverflow?

**Comment by ccloli** [comment]
LGFM, however when I tested the steps on another PC, I found that only install `mingw-w64-x86_64-jsoncpp` will throw an error saying cannot find the reference of JSONCPP when linking, and it can be fixed by installing `jsoncpp-devel` and running CMake again. Maybe you can add `pacman -S jsoncpp-devel` after `pacman -S mingw-w64-x86_64-jsoncpp` in case of missing JSONCPP, thought I'm not sure why it needs a MSYS package, maybe some packages can be used in other compiling environments?

My pleasure, thanks for you invitation. 😉

![image](https://user-images.githubusercontent.com/8115912/56851986-de056200-6947-11e9-9dc1-f6910bcbf16b.png)

![image](https://user-images.githubusercontent.com/8115912/56851909-10fb2600-6947-11e9-918b-9600babd79ab.png)

**Comment by shincurry** [comment]
the last problem, how to distribute full package with both exe and dlls

I have tried these methods from https://github.com/msys2/msys2/wiki/Distributing, but it did not work.

**Comment by ccloli** [comment]
In fact, I don't know either. I did it by running the exe file, and it showed what libraries are missing, then I copied them manually. 😂 

I Googled for a while, but still no luck. Some answers say you can write a shell script to copy them, but I think it's just the same as copy & paste. Some says you can set `set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++ -static")` in `CMakeLists.txt`, however it can only includes static libraries into the binary, shared libraries like OpenCV still needs to be copied manually. If you want to build the file to a single static binary, you may need to build all the dependencies and set `-static` when compiling by yourself

**Comment by shincurry** [comment]
I almost did what you tried. 😂

okay, it can be merged. thank you a lot! 🥳🥳🥳
